rsyslog_conf: "/etc/rsyslog.conf"

elasticsearch_repo: "1.4"
elasticsearch_version: "1.4.2"
elasticsearch_conf: "/etc/elasticsearch/elasticsearch.yml"

logstash_version: "1.4"

nginx_confd: "/etc/nginx/conf.d"

usname: "kibana"
htpass: "kibana"
domain: "kibana"

kibana_url: "https://download.elastic.co/kibana/kibana/kibana-{{ kibana_version }}-{{ kibana_os }}-{{ kibana_arch }}.tar.gz"
kibana_version: "4.0.2"
kibana_os: "linux"
kibana_arch: "x86"
#kibana_arch: "x64"
kibana_host: "0.0.0.0"
kibana_port: "5601"
kibana_elasticsearch: "http://localhost:9200"
kibana_index: ".kibana"

kibana_log: /var/log/kibana.log
kibana_log_rotate_count: 5
kibana_log_rotate_interval: daily